name = "hehehe1341221"
main = "src/worker-v10.js"
compatibility_date = "2026-08-25"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[triggers]
crons = ["*/15 * * * *"]

[[routes]]
pattern = "bot.jean1331.io.vn"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "zalo-bot-db"
database_id = "ea5bd724-63e3-4902-b555-df88f293a46b"
